<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>NameGuard</RootNamespace>
    <AssemblyName>NameGuard</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="CounterStrikeSharp.API">
      <HintPath>CounterStrikeSharp.API.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
